# Generated by Django 5.0.6 on 2024-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('identificacao', models.IntegerField()),
                ('numPaginas', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
