# Generated by Django 5.0.6 on 2024-06-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livros_ano_livros_numpaginas_livros_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='ano',
        ),
    ]
