# Generated by Django 5.0.6 on 2024-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_livros_ano_livros_numpaginas_livros_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='livros',
            name='numPaginas',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='livros',
            name='sinopse',
            field=models.TextField(default='sem sinopse'),
        ),
    ]
