# Generated by Django 5.0.6 on 2024-06-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_livros_ano_alter_livros_numpaginas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='numPaginas',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='sinopse',
        ),
    ]
